apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: openshift-gitops
type: Opaque
stringData:
  AVP_TYPE: vault
  AVP_AUTH_TYPE: k8s
  AVP_K8S_ROLE: mas-gitops-drroc4
  VAULT_ADDR: https://CHANGE_ME_VAULT_ROUTE_OR_SERVICE:8200
  # Optional if using a private CA and AVP image trusts it another way:
  # VAULT_CACERT: /path/in/container/ca.crt
